### ISSUE TITLE
_find request on Filemaker with Flutter

### ISSUE THREAD

**Issue by Lastone17** [LuisMiguelMP/FlutMaker#1]
Hi,

I can also get the Token with Flutter from Filemaker.

But how do I make a _find request?
It's not possible. I always get (Bad Request 400)

I'm sending for example: { "query": [{"searchString": "==teststring"}]}

But server always rejects this request.

Thanks for your help

**Comment by LuisMiguelMP** [comment]
Hi @Lastone17,
Sorry, but I can't test with FileMaker because I haven't more the license.
I expect you solved the problem.
If you have a Flutter issue, let me know and I can help you with that.
